let focusButton = document.getElementById("focus")
let buttons = document.querySelectorAll(".btn")
let shortBreakButton = document.getElementById("shortbreak")
let longBreakButton = document.getElementById("longbreal")
let startBtn = document. getElementById("btn-start")
let reset = document.getElementById("btn-reset")
